#!/bin/sh
for file in $(git diff --cached --name-only --diff-filter=ACM | grep '\.go$'); do
    if ! head -n 1 "$file" | grep -q "Copyright 2026 Q-Tech Team"; then
        echo "Error: Missing copyright header in $file"
        exit 1
    fi
done
