name: qlove
description: Q-Love - Super App Hẹn Hò & Mạng Xã Hội Giải Trí
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  dio: ^5.4.2
  mapbox_maps_flutter: ^2.0.0
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.1
  web_socket_channel: ^3.0.0
  mobile_scanner: ^3.5.6
  qr_flutter: ^4.1.0
  app_links: ^6.1.1
  fl_chart: ^0.66.0
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
