ALTER TABLE card_transactions ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE wall_of_shames ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE vibe_checks ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE card_steals ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
