ALTER TABLE blind_auctions ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE auction_bids ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE ex_ratings ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
